require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FiltersController do

  # This should return the minimal set of attributes required to create a valid
  # Filter. As you add validations to Filter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all filters as @filters" do
      filter = Filter.create! valid_attributes
      get :index
      assigns(:filters).should eq([filter])
    end
  end

  describe "GET show" do
    it "assigns the requested filter as @filter" do
      filter = Filter.create! valid_attributes
      get :show, :id => filter.id
      assigns(:filter).should eq(filter)
    end
  end

  describe "GET new" do
    it "assigns a new filter as @filter" do
      get :new
      assigns(:filter).should be_a_new(Filter)
    end
  end

  describe "GET edit" do
    it "assigns the requested filter as @filter" do
      filter = Filter.create! valid_attributes
      get :edit, :id => filter.id
      assigns(:filter).should eq(filter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filter" do
        expect {
          post :create, :filter => valid_attributes
        }.to change(Filter, :count).by(1)
      end

      it "assigns a newly created filter as @filter" do
        post :create, :filter => valid_attributes
        assigns(:filter).should be_a(Filter)
        assigns(:filter).should be_persisted
      end

      it "redirects to the created filter" do
        post :create, :filter => valid_attributes
        response.should redirect_to(Filter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filter as @filter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filter.any_instance.stub(:save).and_return(false)
        post :create, :filter => {}
        assigns(:filter).should be_a_new(Filter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filter.any_instance.stub(:save).and_return(false)
        post :create, :filter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested filter" do
        filter = Filter.create! valid_attributes
        # Assuming there are no other filters in the database, this
        # specifies that the Filter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Filter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => filter.id, :filter => {'these' => 'params'}
      end

      it "assigns the requested filter as @filter" do
        filter = Filter.create! valid_attributes
        put :update, :id => filter.id, :filter => valid_attributes
        assigns(:filter).should eq(filter)
      end

      it "redirects to the filter" do
        filter = Filter.create! valid_attributes
        put :update, :id => filter.id, :filter => valid_attributes
        response.should redirect_to(filter)
      end
    end

    describe "with invalid params" do
      it "assigns the filter as @filter" do
        filter = Filter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filter.any_instance.stub(:save).and_return(false)
        put :update, :id => filter.id, :filter => {}
        assigns(:filter).should eq(filter)
      end

      it "re-renders the 'edit' template" do
        filter = Filter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filter.any_instance.stub(:save).and_return(false)
        put :update, :id => filter.id, :filter => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filter" do
      filter = Filter.create! valid_attributes
      expect {
        delete :destroy, :id => filter.id
      }.to change(Filter, :count).by(-1)
    end

    it "redirects to the filters list" do
      filter = Filter.create! valid_attributes
      delete :destroy, :id => filter.id
      response.should redirect_to(filters_url)
    end
  end

end
